In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [44]:
df=pd.read_csv('BTC-USD.xls')
df

Date          Open          High           Low         Close  \
0     2014-09-17    465.864014    468.174011    452.421997    457.334015   
1     2014-09-18    456.859985    456.859985    413.104004    424.440002   
2     2014-09-19    424.102997    427.834991    384.532013    394.795990   
3     2014-09-20    394.673004    423.295990    389.882996    408.903992   
4     2014-09-21    408.084991    412.425995    393.181000    398.821014   
...          ...           ...           ...           ...           ...   
2708  2022-02-15  42586.464844  44667.218750  42491.035156  44575.203125   
2709  2022-02-16  44578.277344  44578.277344  43456.691406  43961.859375   
2710  2022-02-17  43937.070313  44132.972656  40249.371094  40538.011719   
2711  2022-02-18  40552.132813  40929.152344  39637.617188  40030.976563   
2712  2022-02-19  40022.132813  40246.027344  40010.867188  40126.429688   

         Adj Close       Volume  
0       457.334015     21056800  
1       424.440002     34483200  
2       394.795990     37919700  
3       408.903992     36863600  
4       398.821014     26580100  
...            ...          ...  
2708  44575.203125  22721659051  
2709  43961.859375  19792547657  
2710  40538.011719  26246662813  
2711  40030.976563  23310007704  
2712  40126.429688  22263900160  

[2713 rows x 7 columns]

Date          Open          High           Low         Close  \
0     2014-09-17    465.864014    468.174011    452.421997    457.334015   
1     2014-09-18    456.859985    456.859985    413.104004    424.440002   
2     2014-09-19    424.102997    427.834991    384.532013    394.795990   
3     2014-09-20    394.673004    423.295990    389.882996    408.903992   
4     2014-09-21    408.084991    412.425995    393.181000    398.821014   
...          ...           ...           ...           ...           ...   
2708  2022-02-15  42586.464844  44667.218750  42491.035156  44575.203125   
2709  2022-02-16  44578.277344  44578.277344  43456.691406  43961.859375   
2710  2022-02-17  43937.070313  44132.972656  40249.371094  40538.011719   
2711  2022-02-18  40552.132813  40929.152344  39637.617188  40030.976563   
2712  2022-02-19  40022.132813  40246.027344  40010.867188  40126.429688   

         Adj Close       Volume  
0       457.334015     21056800  
1       424.440002     34483200  
2       394.795990     37919700  
3       408.903992     36863600  
4       398.821014     26580100  
...            ...          ...  
2708  44575.203125  22721659051  
2709  43961.859375  19792547657  
2710  40538.011719  26246662813  
2711  40030.976563  23310007704  
2712  40126.429688  22263900160  

[2713 rows x 7 columns]

In [45]:
df.drop(['Adj Close'],axis='columns',inplace=True)
df

Date          Open          High           Low         Close  \
0     2014-09-17    465.864014    468.174011    452.421997    457.334015   
1     2014-09-18    456.859985    456.859985    413.104004    424.440002   
2     2014-09-19    424.102997    427.834991    384.532013    394.795990   
3     2014-09-20    394.673004    423.295990    389.882996    408.903992   
4     2014-09-21    408.084991    412.425995    393.181000    398.821014   
...          ...           ...           ...           ...           ...   
2708  2022-02-15  42586.464844  44667.218750  42491.035156  44575.203125   
2709  2022-02-16  44578.277344  44578.277344  43456.691406  43961.859375   
2710  2022-02-17  43937.070313  44132.972656  40249.371094  40538.011719   
2711  2022-02-18  40552.132813  40929.152344  39637.617188  40030.976563   
2712  2022-02-19  40022.132813  40246.027344  40010.867188  40126.429688   

           Volume  
0        21056800  
1        34483200  
2        37919700  
3        36863600  
4        26580100  
...           ...  
2708  22721659051  
2709  19792547657  
2710  26246662813  
2711  23310007704  
2712  22263900160  

[2713 rows x 6 columns]

Date          Open          High           Low         Close  \
0     2014-09-17    465.864014    468.174011    452.421997    457.334015   
1     2014-09-18    456.859985    456.859985    413.104004    424.440002   
2     2014-09-19    424.102997    427.834991    384.532013    394.795990   
3     2014-09-20    394.673004    423.295990    389.882996    408.903992   
4     2014-09-21    408.084991    412.425995    393.181000    398.821014   
...          ...           ...           ...           ...           ...   
2708  2022-02-15  42586.464844  44667.218750  42491.035156  44575.203125   
2709  2022-02-16  44578.277344  44578.277344  43456.691406  43961.859375   
2710  2022-02-17  43937.070313  44132.972656  40249.371094  40538.011719   
2711  2022-02-18  40552.132813  40929.152344  39637.617188  40030.976563   
2712  2022-02-19  40022.132813  40246.027344  40010.867188  40126.429688   

           Volume  
0        21056800  
1        34483200  
2        37919700  
3        36863600  
4        26580100  
...           ...  
2708  22721659051  
2709  19792547657  
2710  26246662813  
2711  23310007704  
2712  22263900160  

[2713 rows x 6 columns]

In [46]:
df['year']=df['Date'].str.split('-',1).str[0]
df['month']=df['Date'].str.split('-',1).str[1].str[:2]
df['day']=df['Date'].str.split('-',1).str[1].str[-2:]
df

C:\Users\parsian\AppData\Local\Temp\ipykernel_8804\3432153112.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df['year']=df['Date'].str.split('-',1).str[0]
C:\Users\parsian\AppData\Local\Temp\ipykernel_8804\3432153112.py:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df['month']=df['Date'].str.split('-',1).str[1].str[:2]
C:\Users\parsian\AppData\Local\Temp\ipykernel_8804\3432153112.py:3: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df['day']=df['Date'].str.split('-',1).str[1].str[-2:]


Date          Open          High           Low         Close  \
0     2014-09-17    465.864014    468.174011    452.421997    457.334015   
1     2014-09-18    456.859985    456.859985    413.104004    424.440002   
2     2014-09-19    424.102997    427.834991    384.532013    394.795990   
3     2014-09-20    394.673004    423.295990    389.882996    408.903992   
4     2014-09-21    408.084991    412.425995    393.181000    398.821014   
...          ...           ...           ...           ...           ...   
2708  2022-02-15  42586.464844  44667.218750  42491.035156  44575.203125   
2709  2022-02-16  44578.277344  44578.277344  43456.691406  43961.859375   
2710  2022-02-17  43937.070313  44132.972656  40249.371094  40538.011719   
2711  2022-02-18  40552.132813  40929.152344  39637.617188  40030.976563   
2712  2022-02-19  40022.132813  40246.027344  40010.867188  40126.429688   

           Volume  year month day  
0        21056800  2014    09  17  
1        34483200  2014    09  18  
2        37919700  2014    09  19  
3        36863600  2014    09  20  
4        26580100  2014    09  21  
...           ...   ...   ...  ..  
2708  22721659051  2022    02  15  
2709  19792547657  2022    02  16  
2710  26246662813  2022    02  17  
2711  23310007704  2022    02  18  
2712  22263900160  2022    02  19  

[2713 rows x 9 columns]

C:\Users\parsian\AppData\Local\Temp\ipykernel_8804\3432153112.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df['year']=df['Date'].str.split('-',1).str[0]
C:\Users\parsian\AppData\Local\Temp\ipykernel_8804\3432153112.py:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df['month']=df['Date'].str.split('-',1).str[1].str[:2]
C:\Users\parsian\AppData\Local\Temp\ipykernel_8804\3432153112.py:3: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df['day']=df['Date'].str.split('-',1).str[1].str[-2:]


Date          Open          High           Low         Close  \
0     2014-09-17    465.864014    468.174011    452.421997    457.334015   
1     2014-09-18    456.859985    456.859985    413.104004    424.440002   
2     2014-09-19    424.102997    427.834991    384.532013    394.795990   
3     2014-09-20    394.673004    423.295990    389.882996    408.903992   
4     2014-09-21    408.084991    412.425995    393.181000    398.821014   
...          ...           ...           ...           ...           ...   
2708  2022-02-15  42586.464844  44667.218750  42491.035156  44575.203125   
2709  2022-02-16  44578.277344  44578.277344  43456.691406  43961.859375   
2710  2022-02-17  43937.070313  44132.972656  40249.371094  40538.011719   
2711  2022-02-18  40552.132813  40929.152344  39637.617188  40030.976563   
2712  2022-02-19  40022.132813  40246.027344  40010.867188  40126.429688   

           Volume  year month day  
0        21056800  2014    09  17  
1        34483200  2014    09  18  
2        37919700  2014    09  19  
3        36863600  2014    09  20  
4        26580100  2014    09  21  
...           ...   ...   ...  ..  
2708  22721659051  2022    02  15  
2709  19792547657  2022    02  16  
2710  26246662813  2022    02  17  
2711  23310007704  2022    02  18  
2712  22263900160  2022    02  19  

[2713 rows x 9 columns]

In [47]:
df.drop(['Date'],axis='columns',inplace=True)
df

Open          High           Low         Close       Volume  \
0       465.864014    468.174011    452.421997    457.334015     21056800   
1       456.859985    456.859985    413.104004    424.440002     34483200   
2       424.102997    427.834991    384.532013    394.795990     37919700   
3       394.673004    423.295990    389.882996    408.903992     36863600   
4       408.084991    412.425995    393.181000    398.821014     26580100   
...            ...           ...           ...           ...          ...   
2708  42586.464844  44667.218750  42491.035156  44575.203125  22721659051   
2709  44578.277344  44578.277344  43456.691406  43961.859375  19792547657   
2710  43937.070313  44132.972656  40249.371094  40538.011719  26246662813   
2711  40552.132813  40929.152344  39637.617188  40030.976563  23310007704   
2712  40022.132813  40246.027344  40010.867188  40126.429688  22263900160   

      year month day  
0     2014    09  17  
1     2014    09  18  
2     2014    09  19  
3     2014    09  20  
4     2014    09  21  
...    ...   ...  ..  
2708  2022    02  15  
2709  2022    02  16  
2710  2022    02  17  
2711  2022    02  18  
2712  2022    02  19  

[2713 rows x 8 columns]

Open          High           Low         Close       Volume  \
0       465.864014    468.174011    452.421997    457.334015     21056800   
1       456.859985    456.859985    413.104004    424.440002     34483200   
2       424.102997    427.834991    384.532013    394.795990     37919700   
3       394.673004    423.295990    389.882996    408.903992     36863600   
4       408.084991    412.425995    393.181000    398.821014     26580100   
...            ...           ...           ...           ...          ...   
2708  42586.464844  44667.218750  42491.035156  44575.203125  22721659051   
2709  44578.277344  44578.277344  43456.691406  43961.859375  19792547657   
2710  43937.070313  44132.972656  40249.371094  40538.011719  26246662813   
2711  40552.132813  40929.152344  39637.617188  40030.976563  23310007704   
2712  40022.132813  40246.027344  40010.867188  40126.429688  22263900160   

      year month day  
0     2014    09  17  
1     2014    09  18  
2     2014    09  19  
3     2014    09  20  
4     2014    09  21  
...    ...   ...  ..  
2708  2022    02  15  
2709  2022    02  16  
2710  2022    02  17  
2711  2022    02  18  
2712  2022    02  19  

[2713 rows x 8 columns]

In [48]:
df.drop(['Open','Low','High'],axis='columns',inplace=True)
df

Close       Volume  year month day
0       457.334015     21056800  2014    09  17
1       424.440002     34483200  2014    09  18
2       394.795990     37919700  2014    09  19
3       408.903992     36863600  2014    09  20
4       398.821014     26580100  2014    09  21
...            ...          ...   ...   ...  ..
2708  44575.203125  22721659051  2022    02  15
2709  43961.859375  19792547657  2022    02  16
2710  40538.011719  26246662813  2022    02  17
2711  40030.976563  23310007704  2022    02  18
2712  40126.429688  22263900160  2022    02  19

[2713 rows x 5 columns]

Close       Volume  year month day
0       457.334015     21056800  2014    09  17
1       424.440002     34483200  2014    09  18
2       394.795990     37919700  2014    09  19
3       408.903992     36863600  2014    09  20
4       398.821014     26580100  2014    09  21
...            ...          ...   ...   ...  ..
2708  44575.203125  22721659051  2022    02  15
2709  43961.859375  19792547657  2022    02  16
2710  40538.011719  26246662813  2022    02  17
2711  40030.976563  23310007704  2022    02  18
2712  40126.429688  22263900160  2022    02  19

[2713 rows x 5 columns]

In [49]:
df.describe()

Close        Volume
count   2713.000000  2.713000e+03
mean   11323.914637  1.470462e+10
std    16110.365010  2.001627e+10
min      178.102997  5.914570e+06
25%      606.718994  7.991080e+07
50%     6317.609863  5.098183e+09
75%    10462.259766  2.456992e+10
max    67566.828125  3.509679e+11

Close        Volume
count   2713.000000  2.713000e+03
mean   11323.914637  1.470462e+10
std    16110.365010  2.001627e+10
min      178.102997  5.914570e+06
25%      606.718994  7.991080e+07
50%     6317.609863  5.098183e+09
75%    10462.259766  2.456992e+10
max    67566.828125  3.509679e+11

In [50]:
df=df.rename(columns={"Close":"Price"})
df

Price       Volume  year month day
0       457.334015     21056800  2014    09  17
1       424.440002     34483200  2014    09  18
2       394.795990     37919700  2014    09  19
3       408.903992     36863600  2014    09  20
4       398.821014     26580100  2014    09  21
...            ...          ...   ...   ...  ..
2708  44575.203125  22721659051  2022    02  15
2709  43961.859375  19792547657  2022    02  16
2710  40538.011719  26246662813  2022    02  17
2711  40030.976563  23310007704  2022    02  18
2712  40126.429688  22263900160  2022    02  19

[2713 rows x 5 columns]

Price       Volume  year month day
0       457.334015     21056800  2014    09  17
1       424.440002     34483200  2014    09  18
2       394.795990     37919700  2014    09  19
3       408.903992     36863600  2014    09  20
4       398.821014     26580100  2014    09  21
...            ...          ...   ...   ...  ..
2708  44575.203125  22721659051  2022    02  15
2709  43961.859375  19792547657  2022    02  16
2710  40538.011719  26246662813  2022    02  17
2711  40030.976563  23310007704  2022    02  18
2712  40126.429688  22263900160  2022    02  19

[2713 rows x 5 columns]

In [51]:
X=df.drop('Price',axis='columns')
y=df.Price

In [52]:
df.dtypes

Price     float64
Volume      int64
year       object
month      object
day        object
dtype: object

Price     float64
Volume      int64
year       object
month      object
day        object
dtype: object

In [53]:
df['year']=df['year'].astype(int)
df['month']=df['month'].astype(int)
df['day']=df['day'].astype(int)

In [54]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [55]:
from sklearn.linear_model import Lasso
lasso=Lasso(alpha=50,max_iter=100,tol=0.1)
lasso.fit(X_train,y_train)

Lasso(alpha=50, max_iter=100, tol=0.1)

Lasso(alpha=50, max_iter=100, tol=0.1)

In [56]:
lasso.score(X_train,y_train)

0.6331073995897601

0.6443462309134413

In [57]:
from sklearn.linear_model import LinearRegression
la=LinearRegression()
la.fit(X_train,y_train)

LinearRegression()

LinearRegression()

In [58]:
la.score(X_train,y_train)

0.6331134567314629

0.6443520728915597

In [59]:
from sklearn.ensemble import GradientBoostingRegressor
gr=GradientBoostingRegressor(max_depth=3,n_estimators=4,learning_rate=0.8)
gr.fit(X_train,y_train)

GradientBoostingRegressor(learning_rate=0.8, n_estimators=4)

GradientBoostingRegressor(learning_rate=0.8, n_estimators=4)

In [60]:
gr.score(X_train,y_train)

0.9766664795114594

0.9772187966646628

In [61]:
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor(n_neighbors=200)
knn.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=200)

KNeighborsRegressor(n_neighbors=200)

In [62]:
knn.score(X_test,y_test)

0.5702008681787167

0.5368511903658153

In [63]:
from sklearn.ensemble import RandomForestRegressor
ra=RandomForestRegressor(n_estimators=220,max_leaf_nodes=220)
ra.fit(X_train,y_train)

RandomForestRegressor(max_leaf_nodes=220, n_estimators=220)

RandomForestRegressor(max_leaf_nodes=220, n_estimators=220)

In [64]:
ra.score(X_test,y_test)

0.9935955183223764

0.9927659925449424

In [65]:
ra.predict([[22263900160,2022,2,20]])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([41677.03405251])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([41048.92687943])

In [66]:
ra.predict([[22263900160,2022,2,21]])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([41133.14963487])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([39396.54721436])

In [67]:
ra.predict([[34263900160,2022,2,22]])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([41324.92165042])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([39335.14738428])

In [68]:
ra.predict([[22263900160,2022,2,23]])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([39806.9866911])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([38344.74180528])

In [69]:
ra.predict([[22263900160,2022,2,24]])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([39440.90366421])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([38113.55173799])

In [70]:
ra.predict([[22263900160,2022,2,25]])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([39325.65197312])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([38132.19354746])

In [71]:
ra.predict([[22263900160,2022,2,26]])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([39318.1185658])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([38142.27296863])

In [72]:
ra.predict([[22263900160,2022,2,27]])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([39382.78348607])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([38211.90623114])

In [73]:
ra.predict([[22263900160,2022,2,28]])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([39424.33363671])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([38375.48547142])

In [74]:
ra.predict([[22263900160,2022,2,29]])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([39251.62791988])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([38239.46059764])

In [75]:
ra.predict([[22263900160,2022,2,30]])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([39239.09049048])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([38236.57432278])

In [76]:
ra.predict([[22263900160,2022,3,1]])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([44980.56144001])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([44672.33495396])

In [77]:
ra.predict([[22263900160,2022,3,2]])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([44591.14335287])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([43497.74334945])

In [78]:
ra.predict([[22263900160,2022,3,3]])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([44337.90239734])

C:\Users\parsian\PycharmProjects\first\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([42352.22150919])

In [79]:
df

Price       Volume  year  month  day
0       457.334015     21056800  2014      9   17
1       424.440002     34483200  2014      9   18
2       394.795990     37919700  2014      9   19
3       408.903992     36863600  2014      9   20
4       398.821014     26580100  2014      9   21
...            ...          ...   ...    ...  ...
2708  44575.203125  22721659051  2022      2   15
2709  43961.859375  19792547657  2022      2   16
2710  40538.011719  26246662813  2022      2   17
2711  40030.976563  23310007704  2022      2   18
2712  40126.429688  22263900160  2022      2   19

[2713 rows x 5 columns]

Price       Volume  year  month  day
0       457.334015     21056800  2014      9   17
1       424.440002     34483200  2014      9   18
2       394.795990     37919700  2014      9   19
3       408.903992     36863600  2014      9   20
4       398.821014     26580100  2014      9   21
...            ...          ...   ...    ...  ...
2708  44575.203125  22721659051  2022      2   15
2709  43961.859375  19792547657  2022      2   16
2710  40538.011719  26246662813  2022      2   17
2711  40030.976563  23310007704  2022      2   18
2712  40126.429688  22263900160  2022      2   19

[2713 rows x 5 columns]

In [80]:


new_data={'Price':[40816,40105,38406,37880,38007,38008,37978,38150,38329,38394,38386,42455,42322,41815],
          'Volume':[22263900160,22263900160,22263900160,22263900160,22263900160,22263900160,22263900160,22263900160,22263900160,22263900160,22263900160,22263900160,22263900160,22263900160],
          'year':[2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022],
          'month':[2,2,2,2,2,2,2,2,2,2,2,3,3,3],
          'day':[20,21,22,23,24,25,26,27,28,29,30,1,2,3]
}
new_data=pd.DataFrame.from_dict(new_data)
new_data


Price       Volume  year  month  day
0   40816  22263900160  2022      2   20
1   40105  22263900160  2022      2   21
2   38406  22263900160  2022      2   22
3   37880  22263900160  2022      2   23
4   38007  22263900160  2022      2   24
5   38008  22263900160  2022      2   25
6   37978  22263900160  2022      2   26
7   38150  22263900160  2022      2   27
8   38329  22263900160  2022      2   28
9   38394  22263900160  2022      2   29
10  38386  22263900160  2022      2   30
11  42455  22263900160  2022      3    1
12  42322  22263900160  2022      3    2
13  41815  22263900160  2022      3    3

Price       Volume  year  month  day
0   40816  22263900160  2022      2   20
1   40105  22263900160  2022      2   21
2   38406  22263900160  2022      2   22
3   37880  22263900160  2022      2   23
4   38007  22263900160  2022      2   24
5   38008  22263900160  2022      2   25
6   37978  22263900160  2022      2   26
7   38150  22263900160  2022      2   27
8   38329  22263900160  2022      2   28
9   38394  22263900160  2022      2   29
10  38386  22263900160  2022      2   30
11  42455  22263900160  2022      3    1
12  42322  22263900160  2022      3    2
13  41815  22263900160  2022      3    3

In [81]:


print(np.mean(new_data.Price))

39360.78571428572
39360.78571428572


In [82]:
print(np.mean(new_data.Price[0:8]))

38668.75
38668.75


In [83]:
print(np.mean(new_data.Price[8:15]))

40283.5
40283.5


In [84]:
data_frame_with_predict=pd.concat([df,new_data])
data_frame_with_predict

Price       Volume  year  month  day
0     457.334015     21056800  2014      9   17
1     424.440002     34483200  2014      9   18
2     394.795990     37919700  2014      9   19
3     408.903992     36863600  2014      9   20
4     398.821014     26580100  2014      9   21
..           ...          ...   ...    ...  ...
9   38394.000000  22263900160  2022      2   29
10  38386.000000  22263900160  2022      2   30
11  42455.000000  22263900160  2022      3    1
12  42322.000000  22263900160  2022      3    2
13  41815.000000  22263900160  2022      3    3

[2727 rows x 5 columns]

Price       Volume  year  month  day
0     457.334015     21056800  2014      9   17
1     424.440002     34483200  2014      9   18
2     394.795990     37919700  2014      9   19
3     408.903992     36863600  2014      9   20
4     398.821014     26580100  2014      9   21
..           ...          ...   ...    ...  ...
9   38394.000000  22263900160  2022      2   29
10  38386.000000  22263900160  2022      2   30
11  42455.000000  22263900160  2022      3    1
12  42322.000000  22263900160  2022      3    2
13  41815.000000  22263900160  2022      3    3

[2727 rows x 5 columns]